name: UbuntuRelease
# CI workflow for Ubuntu builds and testing
on: 
  push:
    branches: ["main"]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: apt-install
      run: |
        sudo apt update
        sudo apt install libusb-1.0-0-dev cmake
    - name: run-cmake
      run: |
        cd ${{github.workspace}}
        mkdir build && cd build
        cmake -DBUILD_TESTING=1 -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      run: |
        cd ${{github.workspace}}/build
        make -j4
    - name: test
      run: |
        cd ${{github.workspace}}/build
        ctest -C Release --timeout 600 --output-on-failure
    - name: pack
      run: |
        cd ${{github.workspace}}/build
        cpack -C Release
    - uses: actions/upload-artifact@v4
      with:
        name: release-deb
        path: |
          ${{github.workspace}}/build/*.deb
          ${{github.workspace}}/build/*.deb.sha256
    - uses: actions/upload-artifact@v4
      with:
        name: release-tar
        path: |
          ${{github.workspace}}/build/*.tar.xz.sha256
          ${{github.workspace}}/build/*.tar.xz
